# Generated by Django 5.2.4 on 2025-07-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('z_coord', models.FloatField(default=0.0)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.floor')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance between the nodes in meters')),
                ('is_accessible', models.BooleanField(default=True, help_text='Whether this path is accessible (e.g. wheelchair accessible)')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='navigation.navigationnode')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='navigation.navigationnode')),
            ],
        ),
    ]
